export const EVENT_CARD_ADDED = 'EVENT_CARD_ADDED';
export const EVENT_CARD_DELETED = 'EVENT_CARD_DELETED';
export const EVENT_CARD_UPDATED = 'EVENT_CARD_UPDATED';

export const EVENT_LIST_ADDED = 'EVENT_LIST_ADDED';