query BoardWithListsAndCards($id: ID!) {
    board(id: $id) {
        title
        color
        lists {
            id
            title
            board_id
            cards {
                id
                title
                order
            }
        }
    }
}
