mutation CardAdd($listId: ID!, $title: String!, $order: Int!, $ownerId: ID!) {
    cardAdd(
        input: {
            title: $title
            list_id: $listId
            order: $order
            owner_id: $ownerId
        }
    ) {
        id
        title
        order
        owner {
            id
        }
    }
}
